// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cosmetics.Models;

public partial class AffiliateLink
{
    public Guid AffiliateLinkId { get; set; }

    public Guid? AffiliateProfileId { get; set; }

    public Guid? ProductId { get; set; }

    public string UniqueCode { get; set; }

    public int? Clicks { get; set; }

    public decimal? EarnedCommission { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreateAt { get; set; }

    public virtual AffiliateProfile AffiliateProfile { get; set; }

    public virtual Product Product { get; set; }
}