// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cosmetics.Models;

public partial class AffiliateCommission
{
    public int CommissionId { get; set; }

    public Guid OrderDetailId { get; set; }

    public Guid AffiliateProfileId { get; set; }

    public decimal CommissionAmount { get; set; }

    public DateTime? EarnedAt { get; set; }

    public bool? IsPaid { get; set; }

    public virtual AffiliateProfile AffiliateProfile { get; set; }

    public virtual OrderDetail OrderDetail { get; set; }
}