// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cosmetics.Models;

public partial class AffiliateProductLink
{
    public int LinkId { get; set; }

    public Guid AffiliateProfileId { get; set; }

    public Guid ProductId { get; set; }

    public string ReferralCode { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual AffiliateProfile AffiliateProfile { get; set; }

    public virtual ICollection<ClickTracking> ClickTrackings { get; set; } = new List<ClickTracking>();

    public virtual Product Product { get; set; }
}