// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cosmetics.Models;

public partial class AffiliateProfile
{
    public Guid AffiliateProfileId { get; set; }

    public int UserId { get; set; }

    public string BankAccount { get; set; }

    public string BankName { get; set; }

    public string PaymentMethod { get; set; }

    public string ApplicationStatus { get; set; }

    public DateTime? CreateAt { get; set; }

    public decimal? TotalEarnings { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<AffiliateLink> AffiliateLinks { get; set; } = new List<AffiliateLink>();

    public virtual ICollection<AffiliatePayment> AffiliatePayments { get; set; } = new List<AffiliatePayment>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual User User { get; set; }
}