// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cosmetics.Models;

public partial class AffiliateProfile
{
    public Guid AffiliateProfileId { get; set; }

    public int UserId { get; set; }

    public string BankName { get; set; }

    public string BankAccountNumber { get; set; }

    public string BankBranch { get; set; }

    public decimal? TotalEarnings { get; set; }

    public decimal? Ballance { get; set; }

    public decimal? PendingAmount { get; set; }

    public decimal? WithdrawnAmount { get; set; }

    public string ReferralCode { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<AffiliateCommission> AffiliateCommissions { get; set; } = new List<AffiliateCommission>();

    public virtual ICollection<AffiliateProductLink> AffiliateProductLinks { get; set; } = new List<AffiliateProductLink>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<TransactionAffiliate> TransactionAffiliates { get; set; } = new List<TransactionAffiliate>();

    public virtual User User { get; set; }
}