// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cosmetics.Models;

public partial class AffiliatePayment
{
    public Guid PaymentId { get; set; }

    public Guid? AffiliateProfileId { get; set; }

    public decimal? Amount { get; set; }

    public string Status { get; set; }

    public DateTime? PaymentDate { get; set; }

    public string TransactionId { get; set; }

    public virtual AffiliateProfile AffiliateProfile { get; set; }
}