// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cosmetics.Models;

public partial class ClickTracking
{
    public int ClickId { get; set; }

    public int LinkId { get; set; }

    public int? UserId { get; set; }

    public int? Count { get; set; }

    public string ReferralCode { get; set; }

    public DateTime? ClickedAt { get; set; }

    public virtual AffiliateProductLink Link { get; set; }

    public virtual User User { get; set; }
}