// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cosmetics.Models;

public partial class Order
{
    public Guid OrderId { get; set; }

    public int? CustomerId { get; set; }

    public int? SalesStaffId { get; set; }

    public Guid? AffiliateProfileId { get; set; }

    public decimal? TotalAmount { get; set; }

    public bool? Status { get; set; }
    //1 : chờ xác nhận
    //2 : xác nhận
    //3 : đang vận chuyển
    //4 : hoàn tất
    //5 : hủy

    public DateTime? OrderDate { get; set; }

    public string PaymentMethod { get; set; }

    public string PaymentStatus { get; set; }

    public virtual AffiliateProfile AffiliateProfile { get; set; }

    public virtual User Customer { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();
}