// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Cosmetics.Enum;
using System;
using System.Collections.Generic;

namespace Cosmetics.Models;

public partial class PaymentTransaction
{
    public Guid PaymentTransactionId { get; set; }

    public Guid OrderId { get; set; }

    public string PaymentMethod { get; set; }

    public string TransactionId { get; set; }

    public string RequestId { get; set; }

    public decimal Amount { get; set; }

    public PaymentStatus Status { get; set; }

    public DateTime TransactionDate { get; set; }

    public int? ResultCode { get; set; }

    public string ResponseTime { get; set; }

    public string OrderInfo { get; set; }

    public virtual Order Order { get; set; }
}