// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cosmetics.Models;

public partial class RolePermission
{
    public Guid? RoleId { get; set; }

    public Guid? PermissionId { get; set; }

    public virtual Permission Permission { get; set; }

    public virtual Role Role { get; set; }
}