// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cosmetics.Models;

public partial class TransactionDetail
{
    public Guid TransactionDetailId { get; set; }

    public Guid? TransactionAffiliatesId { get; set; }

    public string Image { get; set; }

    public virtual TransactionAffiliate TransactionAffiliates { get; set; }
}