// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cosmetics.Models;

public partial class TransactionAffiliate
{
    public Guid TransactionAffiliatesId { get; set; }

    public Guid? AffiliateProfileId { get; set; }

    public decimal Amount { get; set; }

    public DateTime? TransactionDate { get; set; }

    public string Status { get; set; }

    public virtual AffiliateProfile AffiliateProfile { get; set; }
}