name: Build & Test API

on:
  push:
    branches: ["main", "auto-test", "feat/config-auto-test"]
  pull_request:
    branches: ["main", "auto-test", "feat/config-auto-test"]

permissions:
  checks: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Install ReportGenerator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool

      - name: Run tests and collect coverage
        run: |
          dotnet test --no-build --configuration Release \
            --collect:"XPlat Code Coverage" \
            --logger "trx;LogFileName=test-results.trx" \
            --results-directory ./TestResults

      - name: Generate test coverage report
        run: |
          reportgenerator \
            -reports:"**/coverage.cobertura.xml" \
            -targetdir:"./TestResults/html" \
            -reporttypes:Html

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./TestResults/test-results.trx

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./TestResults/html

      - name: Publish test results to PR
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: API Tests
          path: ./TestResults/test-results.trx
          reporter: dotnet-trx
